shell(gitrc): preview git log with fzf and less
note:
the concept is pass the `git log` output to `fzf`, and make keybinding
enter in fzf to trigger `git show` and put it in `less` without leaving
fzf.

credit:
https://github.com/wfxr/forgit/blob/b727321f2bd3d79c1dae805441261c45888cbb41/forgit.plugin.zsh#L17-L34

diff --git a/.config/zsh/gitrc b/.config/zsh/gitrc
--- a/.config/zsh/gitrc
+++ b/.config/zsh/gitrc
@@ -32,8 +32,21 @@ alias \
 	gpl='git pull' \
 	ggl='git pull origin "$(git branch --show-current)"'
 
+# ref: https://github.com/wfxr/forgit/blob/b727321f2bd3d79c1dae805441261c45888cbb41/forgit.plugin.zsh#L17-L34
+# known issue: exit using ctrl-c didn't exit with exit status 0, still not sure why. other than that works fine.
+# it's better to clear the terminal screen before using this, so that less didn't go to the bottom of the screen.
+function gl() {
+	git rev-parse --is-inside-work-tree >/dev/null || return 1
+	local files=$(sed -nE 's/.* -- (.*)/\1/p' <<< "$*")
+	local cmd="echo {} | grep -Eo '[a-f0-9]+' | head -1 | xargs -I% git show --color=always % -- $files"
+
+	# return 0 solve the known issue above, still need to observe this.
+	git log --oneline --color=always --format='%C(auto)%h%d %s %C(black)%C(bold)%cr%Creset' | \
+		fzf --ansi +m --height=100% --tiebreak=index --reverse --bind "enter:execute($cmd | less -r --incsearch)" --preview="$cmd" || \
+		return 0
+}
+
 alias \
-	gl='git log --stat' \
 	glo='git log --graph --oneline' \
 	glg='git log -g' \
 	glp='git log -p'
